name: smart_liveness_detection
description: This package helps you verify that a real person is present in front of the camera, not a photo, video, or mask.
version: 0.0.1-beta.4
homepage: https://github.com/demola234/smart_liveness_detection

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  camera: ^0.11.0+2
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  google_mlkit_face_detection: ^0.9.0
  provider: ^6.1.2
  sensors_plus: ^6.1.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^4.0.0
  dartdoc: ^8.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
